config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :badges, only: :index

  resources :contacts, only: %i[new create]

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one_attached :image
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  RULES = {
    'first_try_pass' => 'First try pass test',
    'lose_10_tests' => 'Lose 10 tests',
    'pass_tests_category' => 'Pass all tests of a category',
    'pass_tests_level' => 'Pass all tests of a level'
  }.freeze
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]
  
  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, success: 'Badge created!'
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, success: 'Badge successfully updated!'
    end

  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :rule, :image, :value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = current_user.badges.order(created_at: :desc)
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td scope="col" class="text-center"><%= badge.title %></td>
  <td scope="col" class="text-center"><%= image_tag badge.image, size: "50x50" %></td>
  <td scope="col" class="text-center"><%= badge.rule %></td>
  <td scope="col" class="text-center"><%= badge.value %></td>
  <td scope="col" class="text-center"><%= link_to 'Show', admin_badge_path(badge) %></td>
  <td scope="col" class="text-center"><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
  <td scope="col" class="text-center">
    <%= link_to 'Delete',
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_title, class: "form-control" %>
  </p>

  <p>
    <%= form.label :rule %><br>
    <%= form.text_field :rule, id: :badge_rule, class: "form-control" %>
  </p>

  <p>
    <%= form.label :value %>
    <%= form.text_field :value, id: :badge_value, class: "form-control" %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image, id: :badge_image, class: "form-control" %>
  </p>

  <p> <%= form.submit %> </p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1>Badges</h1>

<p>
  <%= link_to 'New badge', new_admin_badge_path, class: "btn btn-primary btn-lg" %>
</p>

<table class="table table-hover">
  <tbody>
  <tr class="table-primary">
    <th scope="col" class="text-center">Title</th>
    <th scope="col" class="text-center">Image</th>
    <th scope="col" class="text-center">Rule</th>
    <th scope="col" class="text-center">Value</th>
    <th colspan="3" scope="col" class="text-center">Actions</th>
  </tr>

  <%= render @badges %>
  <tbody>
</table>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong>Title</strong>
  <%= @badge.title %>
</p>

<p>
  <strong>Image</strong>
  <%= @badge.image %>
</p>

<p>
  <strong>Rule</strong>
  <%= @badge.rule %>
</p>

<p>
  <strong>Value</strong>
  <%= @badge.value %>
</p>

<%= link_to 'Edit', edit_admin_badge_path(@badge) %>
<%= link_to 'Back', admin_badges_path %>