config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :badges, only: :index

  resources :contacts, only: %i[new create]

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :number_of_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def number_of_answers
    errors.add(:base, 'Count of answers must be 1 to 4') if question.answers.count > 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one_attached :image
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  RULES = {
    'first_try_pass' => 'First try pass test',
    'lose_10_tests' => 'Lose 10 tests',
    'pass_tests_category' => 'Pass all tests of a category',
    'pass_tests_level' => 'Pass all tests of a level'
  }.freeze
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name
  attribute :email
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    { 
      subject: "My contact form",
      to: "thejadeonwot@gmail.com",
      from: %("#{name}" "#{email}")
    }
  end
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, foreign_key: 'current_question_id'

  validates :body, presence: true
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { case_sensitive: false, scope: :level,
                                  message: 'There can only be one test with a given name and level' }

  scope :test_level_easy, -> { where(level: (0..1)) }
  scope :test_level_middle, -> { where(level: (2..4)) }
  scope :test_level_hard, -> { where(level: (5..Float::INFINITY)) }

  scope :test_names, lambda { |category_title|
    joins(:category)
      .where(categories: { title: category_title })
      .order(title: :DESC)
  }

  def self.test_names_title(category_title)
    test_names(category_title).pluck(:title)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  SUCCESS_RATIO = 85

  def current_question_number
    self.test.questions.index(current_question) + 1
  end

  def total_questions
    test.questions.count
  end

  def completed?
    current_question.nil? || difference_time.zero?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def update_successfull!
    update(successfull: true)
  end

  def success?
    success_rate >= SUCCESS_RATIO
  end

  def success_rate
    (correct_questions.to_f * 100) / test.questions.size
  end

  def timer_deadline
    self.created_at + (self.test.timer * 60)
  end

  def difference_time
    (timer_deadline - time_now).floor
  end

  def time_now
    Time.now
  end

  private

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question.nil?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def before_validation_set_current_question
    self.current_question = next_question
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :having_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def passed_tests(test_level)
    tests.where(level: test_level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = current_user.badges.order(created_at: :desc)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/gists_controller.rb
# frozen_string_literal: true

class GistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @test_passage = TestPassage.find(params[:test_passage_id])
    service = GistQuestionService.new(@test_passage.current_question)

    url = service.call.html_url

    if service.success?
      current_user.gists.create(question: @test_passage.current_question, gist_url: url)

      flash[:notice] = t('.success', link: url)
    else
      flash[:error] = t('.failure')
    end

    redirect_to @test_passage
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])

    if @test.completed
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    else
      redirect_to root_path, warning: 'Нет доступа к тесту!'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  FLASH_TYPES = {
    notice: 'alert-info',
    warning: 'alert-warning',
    success: 'alert-success'
  }

  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to 'GitHub', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_messages(type)
    content_tag :div, flash[type], class: "alert #{FLASH_TYPES[type]}" if flash[type].present?
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    if question.new_record?
      t('.shared.message.new_question')
    else
      t('.shared.message.edit_question')
    end
  end
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
  TEST_LEVELS = { 0 => :beginner, 1 => :elementary,
                  2 => :intermediate, 3 => :advanced }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/_nav.html.erb
<div class="container">
  <ul class="nav justify-content-end mt-3">
    <li class="nav-item">
      <%= link_to 'Badges', admin_badges_path, class: 'nav-link active' %>
    </li>
    <li class="nav-item">
      <%= link_to t('shared.links.main'), admin_tests_path, class: 'nav-link active' %>
    </li>
    <li class="nav-item">
      <a class="nav-link active>"> <%= t('shared.message.welcome') %><%= current_user.email %> Guru </a>
    </li>
    <li>
      <%= button_to t('shared.links.logout'), destroy_user_session_path, method: :delete, class: 'nav-link active' %>
    </li>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Admin Panel | Test Guru </title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'admin/nav' %>

<div class="container">
  <%= flash_messages(:success) %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <hr>
  <%= debug(params) if Rails.env.development? %>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=devise-width, initial-scale=1, shrink-to-fit=no">

    <title>Testguru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= flash_messages(:warning) %>
      <%= flash_messages(:success) %>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<main class="container mt-3">
  <% if resource.present? && resource.errors.any? %>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
        <h2> <%= t('.header', count: resource.errors.count) %>: </h2>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li> <%= message  %> </li>
          <% end %>
        </ul>
    <% end %>
  <% end %>
</main>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container d-flex justify-content-center fixed-bottom">
    <span class="text-muted">
      <%= current_year %>
      |
      <%= t('.author') %>
      |
      <%= github_url('Eviljadeon', 'TestGuru') %>
      |
      <%= link_to t('.project'), 'https://thinknetica.com', target: '_blank', class: 'text-muted' %>
      |
      <%= link_to t('.feedback'), new_contact_path, class: 'text-muted' %>
    </span>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="container">
  <ul class="nav justify-content-end mt-3">
    <% if current_user.is_a?(Admin) %>
      <li class="nav-item ">

      <%= link_to  t('admin.nav.header'), admin_tests_path, class: 'nav-link active' %>
    <% end %>
    </li>

    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'My badges', badges_path, class: 'nav-link active' %>
      </>

      <li class="nav-item">
        <%= link_to t('.header'), root_path, class: 'nav-link active' %>
      </li>

      <li class="nav-item ">
      <a class="nav-link active">
        Welcome, <b> <%= current_user.first_name %> </b> Guru
      </a>
     </li>
    <li class="nav-item">
      <%= button_to t('shared.links.logout'), destroy_user_session_path, method: :delete, class: 'nav-link active' %>
    </li>
    <% else %>
      <li class="nav-item">
        <%= link_to t('shared.links.signup'), new_user_registration_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to t('shared.links.login'), user_session_path, class: 'nav-link active' %>
      </li>
    <% end %>
  </ul>
</div>