config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :badges, only: :index

  resources :contacts, only: %i[new create]

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, foreign_key: 'current_question_id'

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  SUCCESS_RATIO = 85

  def current_question_number
    self.test.questions.index(current_question) + 1
  end

  def total_questions
    test.questions.count
  end

  def completed?
    current_question.nil? || difference_time.zero?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def update_successfull!
    update(successfull: true)
  end

  def success?
    success_rate >= SUCCESS_RATIO
  end

  def success_rate
    (correct_questions.to_f * 100) / test.questions.size
  end

  def timer_deadline
    self.created_at + (self.test.timer * 60)
  end

  def difference_time
    (timer_deadline - time_now).floor
  end

  def time_now
    Time.now
  end

  private

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question.nil?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def before_validation_set_current_question
    self.current_question = next_question
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update

    @test_passage.accept!(params[:answer_ids])
   
    if @test_passage.completed?

      @test_passage.update_successfull! if @test_passage.success?

      BadgeService.new(@test_passage).call

      TestsMailer.completed_test(@test_passage).deliver_now
    
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% if @test_passage.success? %>
  <h1><font color="green"><%= t('.success') %></font></h1>
<% else %>
  <h1><font color="red"><%= t('.fail') %></font></h1>
<% end %>    

<%= link_to t('.shared.button.back_to_tests'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<b>
  <%= t('.current_question', number: @test_passage.current_question_number) %> <%= t('.of') %> <%= t('.total_questions', count: @test_passage.test.questions.count) %> #
</b>

<p>
<%= flash_messages(:notice) %>
<%= flash_messages(:error) %>
</p>

<%= content_tag :div, nil,  class: 'progressbar', data: { current_question_number: @test_passage.current_question_number,
                                                      total_questions: @test_passage.total_questions } %>

                                            

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), id: 'navform', method: :put, data: { difference_time: @test_passage.difference_time } do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to t('shared.links.new_gist'), gists_path(test_passage_id: @test_passage.id), method: :post %></p>
  <p><%= form.submit t('.button.next') %></p>

<% end %>

<%= content_tag :div, nil, class: 'timer' do %>
  <li><span id="minutes"><%= @test_passage.test.timer %></span>Minutes</li>
  <li><span id="seconds">00</span>Seconds</li>
<% end %>