config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :badges, only: :index

  resources :contacts, only: %i[new create]

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, foreign_key: 'current_question_id'

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

  class Admin::QuestionsController < Admin::BaseController
    before_action :find_test, only: %i[create new]
    before_action :find_question, only: %i[show edit update destroy]

    rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

    def show; end

    def new
      @question = Question.new
    end

    def edit; end

    def create
      @question = @test.questions.new(question_params)

      if @question.save
        redirect_to admin_test_path(@question.test), success: t('.success')
      else
        render :new
      end
    end

    def update
      if @question.update(question_params)
        redirect_to admin_test_path(@question.test), success: t('.update_success')
      else
        render :edit
      end
    end

    def destroy
      @question.destroy
      redirect_to admin_test_path(@question.test), notice: t('.delete')
    end

    private

    def find_test
      @test = Test.find(params[:test_id])
    end

    def find_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:body)
    end

    def rescue_with_question_not_found
      render html: '<h3>Question not found</h3>'.html_safe
    end
  end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    if question.new_record?
      t('.shared.message.new_question')
    else
      t('.shared.message.edit_question')
    end
  end
end

app/views/admin/questions/_form.html.erb
<h2><%= question_header(@question) %></h2>

<%= form_with model: [:admin, @test, @question] do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<ul>
  <tr>
    <td><%= question.body %></td>
    <td><%= link_to t('.shared.links.edit'), edit_admin_question_path(question) %></td>
    <td><%= link_to t('.shared.links.delete'), admin_question_path(question),
                              method: :delete,
                              data: { confirm: t('.shared.delete_confirmation') } %>
    </td>
  </tr>
</ul>

app/views/admin/questions/edit.html.erb
<h1><%= t('.edit', body: @question.body) %></h1>

<p><%= @question.body %></p>

<h2><%= t('.answers') %></h2>

<%= link_to t('.new.header'), new_admin_question_answer_path(@question) %>

<ol><%= render @question.answers %></ol>

<%= link_to t('.shared.links.edit'), edit_admin_question_path(@question) %>
<%= link_to t('.shared.links.back'), admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form' %>

<%= link_to t('.shared.links.back'), admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= t('.show.body') %></h1>

<p><%= @question.body %></p>

<h2><%= t('.answers') %></h2>

<%= link_to t('.shared.links.new_answer'), new_admin_question_answer_path(@question) %>

<ol><%= render @question.answers %></ol>

<%= link_to t('.shared.links.edit'), edit_admin_question_path(@question) %>
<%= link_to t('.shared.links.back'), admin_test_path(@question.test) %>